version: '2'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports: 
        - "9000:9000"
    volumes:
        - .:/frontend
        - ~/.gu:/root/.gu
        - ~/.aws:/root/.aws
        # Mount cache directories
        - ~/.npm:/root/.npm
        - ~/.sbt:/root/.sbt
        - ~/.ivy2:/root/.ivy2
